#include <openxr/openxr.h>
#define XR_USE_PLATFORM_ANDROID
#define XR_USE_GRAPHICS_API_OPENGL_ES
#include <android_native_app_glue.h>
#include <android/native_activity.h>
#include <android/log.h>
#include <android/sensor.h>
#include <EGL/egl.h>
#include <GLES/gl.h>
#include <GLES3/gl3.h>
#include <GLES3/gl31.h>
#include <openxr/openxr_platform.h>
#include <sys/system_properties.h>
#include "android_helper.h"
